### PR TITLE
Add optional precision kwarg for formatting floating point data

### PR DESCRIPTION
**Pull request by brentru**
Added `precision` kwarg to `send_data` to truncate floating point values to a specified `precision` decimal places before the payload is created and sent to Adafruit IO.

Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/12

Tested with PyPortal

### CODE REVIEW

**Comment by brentru** [comment]
@jerryneedell  I think this is OK for now as far as formatting, but would be open to other ideas.

**Comment by jerryneedell** [comment]
just setting up a test

**Comment by jerryneedell** [comment]
```Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-141-g2c9fbb5d4 on 2019-02-24; Adafruit ItsyBitsy M4 Express with samd51g19
>>> 
>>> import ibm4_aio_data
Failed to connect, retrying
 ('No such ssid', b'Needell Airport')
Sending 9 to temperature feed...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibm4_aio_data.py", line 67, in <module>
  File "adafruit_io/adafruit_io.py", line 145, in send_data
NotImplementedError: 
>>> 
```

**Comment by jerryneedell** [comment]
I modified the "data" simpletest to this ```
# Send random integer values to the feed
random_value = randint(0, 50)
print('Sending {0} to temperature feed...'.format(random_value))
io.send_data(temperature_feed['key'], random_value, metadata=None, precision=1)
print('Data sent!')

```
and I get this error on my ItsyBitsy_M4
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-141-g2c9fbb5d4 on 2019-02-24; Adafruit ItsyBitsy M4 Express with samd51g19
>>> 
>>> import ibm4_aio_data
Failed to connect, retrying
 ('No such ssid', b'Needell Airport')
Sending 30 to temperature feed...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibm4_aio_data.py", line 67, in <module>
  File "adafruit_io/adafruit_io.py", line 146, in send_data
NotImplementedError: 
>>> 
```

**Comment by jerryneedell** [comment]
fixed -- the data value cannot be an "int"  must be float. It does not make sense to "round" an int anyway but will this cause any unexpected errors?

**Comment by brentru** [comment]
Thanks for the catch for `ints` - I'll add handling for if a non-floating point value is passed in

**Comment by brentru** [comment]
Added a check for incorrect data types, throwing an error.

**Pull request merged**
