### PR TITLE
Add TypeHints to adafruit_io.py

### LINKED ISSUE #79: Missing Type Annotations
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_io/adafruit_io_errors.py:20
- [ ] adafruit_io/adafruit_io_errors.py:31
- [ ] adafruit_io/adafruit_io.py:37
- [ ] adafruit_io/adafruit_io.py:60
- [ ] adafruit_io/adafruit_io.py:93
- [ ] adafruit_io/adafruit_io.py:123
- [ ] adafruit_io/adafruit_io.py:134
- [ ] adafruit_io/adafruit_io.py:142
- [ ] adafruit_io/adafruit_io.py:182
- [ ] adafruit_io/adafruit_io.py:188
- [ ] adafruit_io/adafruit_io.py:193
- [ ] adafruit_io/adafruit_io.py:209
- [ ] adafruit_io/adafruit_io.py:221
- [ ] adafruit_io/adafruit_io.py:236
- [ ] adafruit_io/adafruit_io.py:280
- [ ] adafruit_io/adafruit_io.py:288
- [ ] adafruit_io/adafruit_io.py:300
- [ ] adafruit_io/adafruit_io.py:311
- [ ] adafruit_io/adafruit_io.py:351
- [ ] adafruit_io/adafruit_io.py:379
- [ ] adafruit_io/adafruit_io.py:440
- [ ] adafruit_io/adafruit_io.py:465
- [ ] adafruit_io/adafruit_io.py:476
- [ ] adafruit_io/adafruit_io.py:483
- [ ] adafruit_io/adafruit_io.py:496
- [ ] adafruit_io/adafruit_io.py:507
- [ ] adafruit_io/adafruit_io.py:514
- [ ] adafruit_io/adafruit_io.py:528
- [ ] adafruit_io/adafruit_io.py:541
- [ ] adafruit_io/adafruit_io.py:555
- [ ] adafruit_io/adafruit_io.py:575
- [ ] adafruit_io/adafruit_io.py:586
- [ ] adafruit_io/adafruit_io.py:596
- [ ] adafruit_io/adafruit_io.py:605
- [ ] adafruit_io/adafruit_io.py:616
- [ ] adafruit_io/adafruit_io.py:626
- [ ] adafruit_io/adafruit_io.py:634
- [ ] adafruit_io/adafruit_io.py:642
- [ ] adafruit_io/adafruit_io.py:652
- [ ] adafruit_io/adafruit_io.py:664
- [ ] adafruit_io/adafruit_io.py:677
- [ ] adafruit_io/adafruit_io.py:689
- [ ] adafruit_io/adafruit_io.py:699
- [ ] adafruit_io/adafruit_io.py:708

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
Resolves #79

### CODE REVIEW

**Comment by tekktrik** [comment]
Looks like this is failing the CI.  You can use `pre-commit` to help fix the issues it's having.  You can find information on how to install and use `pre-commit` here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Review by tekktrik — CHANGES_REQUESTED** [review]
See above :)

**Review by FoamyGuy — CHANGES_REQUESTED** [review]
I added a commit that fixed up the actions issues and merged the latest from main.

I've had a look over this and found a few things I think we'll want to have changed.

**Review by FoamyGuy — APPROVED** [review]
The latest commit addresses all requested changes. 

The current version is looking good to me. 

Thanks again for making this contribution!

**Comment by FoamyGuy** [comment]
I had another look over this one. Going to merge it. Any further changes or adjustments can come in a followup PR / issue.

**Pull request merged**
