### PR TITLE
Update for settings.toml (CPY8) and SSL.

### PR DESCRIPTION
**Pull request by tyeth**
Tested on Adafruit Feather ESP32-S2 Reverse TFT with CPY 8.2.4.

Paul Cutler raised an issue in discord about using SSL and miniMQTT with the IO library, and I realised I hadn't retested with SSL in circuitpython for a while especially since Root cert updates. The version Paul was using was 8.2.2 which has an SSL issue connecting to api.github.com so advised to update to latest CPY of 8.2.4 to get up to date root certs.

This brings the demo for the esp32s2 up to scratch, working with secrets.py or settings.toml, and optionally connecting to wifi. The port is also changed and is_ssl=True to enable SSL.

### CODE REVIEW

**Comment by tyeth** [comment]
@brentru  This relates to #99

**Comment by brentru** [comment]
@prcutler Could you test if this fixes https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/107?

**Comment by tyeth** [comment]
Just to add the root certs in CPY 8.2.4 still fail with API.github.com but Dan will cut a new release with updated root certs this week (8.2.5)
There's an open issue in the Adafruit nina-fw repo

**Comment by prcutler** [comment]
I will test this, but probably not until tomorrow (sorry!).  Tyeth was able to help get me working code to use `io.connect()` but I will try the simpletest out. Thanks for the quick responses!

**Review by FoamyGuy — APPROVED** [review]
This looks good to me. I tested it successfully on a Feather ESP32-S2 TFT with CircuitPython `8.2.6`

**Comment by luke-edward** [comment]
> prcutler

How were you able to get io.connect() working?

**Comment by prcutler** [comment]
Looking at my code, it looks like I used normal MQTT and not `io.connect`.  It looks like the original issue was due to a root certificate problem, it should work on 8.2.9 or later.

**Pull request merged**
